name: Generate snake animation

on:
  schedule: # every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: rakshithakb5
          outputs: |
            dist/snake.svg?color_snake=purple&color_dots=%230d1117,%23141a23,%231f2d3a,%23238636,%2339d353

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
