name: Generate snake animation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: rakshithakb5
          outputs: |
            dist/snake.svg?color_snake=purple&color_dots=%230d1117,%230f1623,%231a2634,%23238636,%2339d353
