
name: Generate snake animation

on:
  schedule:
    - cron: "0 0 * * *"   # run daily at 00:00 UTC
  workflow_dispatch:       # allow manual runs

permissions:
  contents: write          # needed to push to "output" branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVG (dark gray grid + purple snake)
        uses: Platane/snk@v3
        with:
          github_user_name: rakshithakb5
          # five levels (0 → 4). hex colors must be URL-encoded as %23
          outputs: |
            dist/snake.svg?color_snake=purple&color_dots=%23262626,%23333333,%23444444,%23238636,%2339d353

      - name: Publish SVG to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
